name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and deploy
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Build
      run: ${{ cmd }}
      env:
        cmd: echo 5
