name: Build and Deploy

on:
  push:
    branches:
      - master
    paths-ignore:
      - '*.md'
      - '.idea/*'
      - '.vs/*'


jobs:
  build:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Build
      run: echo $hmmm
      env:
        hmmm: 5
